# Sorting Galaxies: (Type 0 - Type 1.5)

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Read all files

In [4]:
catgama = pd.read_csv('InputCatGAMADR3.csv')
catclusters = pd.read_csv('samiDR3InputCatClusters.csv')
stelkin = pd.read_csv('samiDR3StelKin.csv')
vismorph = pd.read_csv('samiDR3VisualMorphology.csv')

In [6]:
stelkinids = set(stelkin['catid'])
vismorphids = set(vismorph['catid'])
same = (stelkinids == vismorphids)

print(len(stelkinids))
print(len(vismorphids))
same

3068
3068

True

**stelkin and vismorph contain the same galaxies**

In [9]:
print(len(stelkin))
print(len(stelkinids))

print(len(vismorph))
print(len(vismorphids))

3426
3068
3068
3068

Duplicated catids in stelkin to be removed before merge 
(noticed longer stelkin file but found same number of galaxies before)

In [12]:
stelkin = stelkin.drop_duplicates(subset='catid')

Sort these galaxies by type

In [15]:
mask = (vismorph['type'] >= 0.0) & (vismorph['type'] <= 1.5)
etg = vismorph[mask]

note: this exclude unclassified galaxies (type < 0)

To plot FJ relation, sigma_re is required. Therefore, galaxies must appear in stelkin to be plotted. Since stelking and vismorph contain the same galaxies, sorting vismorph is sufficient for plot.

In [27]:
etg_sigma = pd.merge(etg, stelkin[['catid','sigma_re']], on='catid')
(etg_sigma)

      Unnamed: 0       catid  type    sigma_re
0              2        7139   1.0  235.612810
1              4        7289   0.5  205.145280
2              5        7715   0.5         NaN
3              6        7839   0.5  195.761120
4              7        7841   1.5  178.646880
...          ...         ...   ...         ...
1284        3062  9403801183   1.5         NaN
1285        3063  9403801268   1.5         NaN
1286        3065  9403801281   1.5   57.441160
1287        3066  9403801368   0.0         NaN
1288        3067  9403801579   0.0   52.304882

[1289 rows x 4 columns]

In [38]:
catgama_mstar = pd.merge(etg_sigma, catgama[['catid','mstar']], on='catid')
catclusters_mstar = pd.merge(etg_sigma, catclusters[['catid','mstar']], on='catid')
etg_sigma_mstar = pd.concat([catgama_mstar, catclusters_mstar])
(etg_sigma_mstar)

     Unnamed: 0       catid  type    sigma_re      mstar
0             2        7139   1.0  235.612810  10.630000
1             4        7289   0.5  205.145280  11.120000
2             5        7715   0.5         NaN  10.990000
3             6        7839   0.5  195.761120  11.050000
4             7        7841   1.5  178.646880  10.960000
..          ...         ...   ...         ...        ...
605        3062  9403801183   1.5         NaN  10.734562
606        3063  9403801268   1.5         NaN  10.519668
607        3065  9403801281   1.5   57.441160   9.801854
608        3066  9403801368   0.0         NaN  11.465432
609        3067  9403801579   0.0   52.304882   9.642783

[1262 rows x 5 columns]

note: not all galaxies from etg_sigma have a matching mstar

In [41]:
etg_sigma_mstar_cleaned = etg_sigma_mstar.dropna(subset=['sigma_re'])
(etg_sigma_mstar_cleaned)

     Unnamed: 0       catid  type    sigma_re      mstar
0             2        7139   1.0  235.612810  10.630000
1             4        7289   0.5  205.145280  11.120000
3             6        7839   0.5  195.761120  11.050000
4             7        7841   1.5  178.646880  10.960000
5             9        7969   0.5  249.797650  11.020000
..          ...         ...   ...         ...        ...
601        3056  9403801002   0.0  115.781456  10.361357
602        3057  9403801010   1.0  207.550350  10.677064
603        3058  9403801061   1.5   74.888490  10.300241
607        3065  9403801281   1.5   57.441160   9.801854
609        3067  9403801579   0.0   52.304882   9.642783

[1051 rows x 5 columns]